/**
 * PHASE 25: Bibliothèque de Modèles & Presets Métiers
 * Modèles pré-configurés pour déployer des flipbooks adaptés aux secteurs clés
 * (Hôtellerie de luxe, Immobilier, Restauration, Mode, Corporate, B2B).
 */

import { FlipbookTemplatePreset } from '../types/saas';

export const TEMPLATE_PRESETS: FlipbookTemplatePreset[] = [
  {
    id: 'tpl-palace',
    name: 'Palace & Hôtellerie de Luxe',
    category: 'HOSPITALITY',
    description: 'Palette Champagne & Or, bouton de réservation WhatsApp, ambiance musicale lounge, formulaire conciergerie.',
    sampleHotspotsCount: 8,
    recommendedAspect: 'A4',
    previewImageUrl: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=600&q=80',
    themeConfig: {
      primaryColor: '#D4AF37',
      accentColor: '#F7E7CE',
      backgroundColor: '#0F0E0C',
      surfaceColor: '#1A1815',
      textColor: '#FFFFFF',
      dockStyle: 'floating',
      bookSpineColor: '#2D281E',
      borderRadiusPx: 12,
    },
  },
  {
    id: 'tpl-immo',
    name: 'Immobilier de Prestige',
    category: 'REAL_ESTATE',
    description: 'Plans interactifs, visite vidéo drone intégrée, demande de dossier notarié, localisation cartographique.',
    sampleHotspotsCount: 12,
    recommendedAspect: '16:9',
    previewImageUrl: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=600&q=80',
    themeConfig: {
      primaryColor: '#0284C7',
      accentColor: '#38BDF8',
      backgroundColor: '#090D16',
      surfaceColor: '#111827',
      textColor: '#FFFFFF',
      dockStyle: 'bottom-bar',
      bookSpineColor: '#1E293B',
      borderRadiusPx: 8,
    },
  },
  {
    id: 'tpl-restaurant',
    name: 'Haute Gastronomie & Carte des Vins',
    category: 'GASTRONOMY',
    description: 'Menu dégustation shoppable, accords mets & vins, allergènes interactifs, commande en salle via QR Code.',
    sampleHotspotsCount: 15,
    recommendedAspect: 'A4',
    previewImageUrl: 'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?auto=format&fit=crop&w=600&q=80',
    themeConfig: {
      primaryColor: '#E11D48',
      accentColor: '#FDA4AF',
      backgroundColor: '#130B0E',
      surfaceColor: '#1F1217',
      textColor: '#FFF1F2',
      dockStyle: 'floating',
      bookSpineColor: '#381622',
      borderRadiusPx: 10,
    },
  },
  {
    id: 'tpl-fashion',
    name: 'Lookbook Mode & Fashion',
    category: 'FASHION',
    description: 'Design minimaliste épuré, fiches produits pop-up avec variantes (tailles/couleurs), panier d’achat direct.',
    sampleHotspotsCount: 10,
    recommendedAspect: 'A4',
    previewImageUrl: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=600&q=80',
    themeConfig: {
      primaryColor: '#FFFFFF',
      accentColor: '#A1A1AA',
      backgroundColor: '#000000',
      surfaceColor: '#18181B',
      textColor: '#FFFFFF',
      dockStyle: 'minimalist-top',
      bookSpineColor: '#27272A',
      borderRadiusPx: 4,
    },
  },
  {
    id: 'tpl-corporate',
    name: 'Rapport Annuel & RSE',
    category: 'CORPORATE',
    description: 'Typographie institutionnelle, table des matières hiérarchique, recherche plein-texte, téléchargement PDF certifié.',
    sampleHotspotsCount: 6,
    recommendedAspect: 'A4',
    previewImageUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=600&q=80',
    themeConfig: {
      primaryColor: '#4F46E5',
      accentColor: '#818CF8',
      backgroundColor: '#0B0F19',
      surfaceColor: '#111827',
      textColor: '#F3F4F6',
      dockStyle: 'bottom-bar',
      bookSpineColor: '#1E1B4B',
      borderRadiusPx: 6,
    },
  },
  {
    id: 'tpl-retail',
    name: 'Catalogue B2B & Distributeurs',
    category: 'RETAIL',
    description: 'Catalogue de pièces, devis express par page, gate lock avec capture de SIRET et email professionnel.',
    sampleHotspotsCount: 20,
    recommendedAspect: 'A4',
    previewImageUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=600&q=80',
    themeConfig: {
      primaryColor: '#10B981',
      accentColor: '#6EE7B7',
      backgroundColor: '#06130E',
      surfaceColor: '#0E241B',
      textColor: '#ECFDF5',
      dockStyle: 'bottom-bar',
      bookSpineColor: '#064E3B',
      borderRadiusPx: 8,
    },
  },
];
